### ISSUE TITLE
`choco install fluidsynth` v2.4.3 works but the default v2.4.4 fails

### ISSUE THREAD

**Issue by cclauss** [FluidSynth/fluidsynth#1541]
* https://github.com/cclauss/fluidsynth-tests
* https://github.com/cclauss/fluidsynth-tests/actions

### `choco install fluidsynth` v2.4.3 works but the default v2.4.4 fails.
```yaml
name: choco
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        fluidsynth-version: [2.4.3, 2.4.4]
    runs-on: windows-latest
    steps:  # fluidsynth v2.4.3 works but the default v2.4.4 fails.
      - run: choco install fluidsynth --version ${{ matrix.fluidsynth-version }}
      - run: fluidsynth --version
```
